### PR TITLE
migrate algos to promsified common

### PR DESCRIPTION
**Pull request by cdaringe**
@ref https://github.com/MRN-Code/coinstac-common/pull/52

### CODE REVIEW

**Comment by swashcap** [comment]
Linked everything up. There's no definitive "tests have passed" output when running `npm test`. Should I run something else? Seeing this:

```shell
error: USER: minionA I read and parsed a file.  It's value is: A
info: COMPUTE-SERVER: { minionA: { value: 'A' } }
error: USER: minionB Callback was already called.
Error: Callback was already called.
    at /Users/creed/coinstac/simulator/node_modules/async/lib/async.js:43:36
    at /Users/creed/coinstac/simulator/node_modules/async/lib/async.js:723:17
    at /Users/creed/coinstac/simulator/node_modules/async/lib/async.js:167:37
    at remoteResultDB.all (/Users/creed/coinstac/simulator/src/boot-client.js:130:13)
    at tryCatcher (/Users/creed/coinstac/common/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Users/creed/coinstac/common/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/Users/creed/coinstac/common/node_modules/bluebird/js/release/promise.js:556:21)
    at Promise._settlePromise0 (/Users/creed/coinstac/common/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/creed/coinstac/common/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/creed/coinstac/common/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/creed/coinstac/common/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/creed/coinstac/common/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
/Users/creed/coinstac/simulator/src/boot-client.js:180
  throw err;
  ^

Error: Callback was already called.
    at /Users/creed/coinstac/simulator/node_modules/async/lib/async.js:43:36
    at /Users/creed/coinstac/simulator/node_modules/async/lib/async.js:723:17
    at /Users/creed/coinstac/simulator/node_modules/async/lib/async.js:167:37
    at remoteResultDB.all (/Users/creed/coinstac/simulator/src/boot-client.js:130:13)
    at tryCatcher (/Users/creed/coinstac/common/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Users/creed/coinstac/common/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/Users/creed/coinstac/common/node_modules/bluebird/js/release/promise.js:556:21)
    at Promise._settlePromise0 (/Users/creed/coinstac/common/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/creed/coinstac/common/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/creed/coinstac/common/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/creed/coinstac/common/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/creed/coinstac/common/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
/Users/creed/coinstac/simulator/src/boot-clients.js:35
          throw new Error(`user process exited with ${code}`);
          ^

Error: user process exited with 7
    at ChildProcess.userProcess.on (/Users/creed/coinstac/simulator/src/boot-clients.js:35:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by cdaringe** [comment]
The latest common doesn't use callbacks in the command computation
anymore.  Something is wrong with the linking.  An old common is still
being used

**Comment by cdaringe** [comment]
Oh, I thought the error was something else.  I check this out in a bit

**Comment by cdaringe** [comment]
still not sure what the issue is.  i do think something may not be fully linked or all on the right branch (feature/promisify).

also, yea, by this point, there aren't assertions made.  they'd be nice to add, but honestly convergence and/or halting (w/ 0 exit codes) are actually pretty good tests on their own.  would def like to add some assertions at soon!

check it:

```bash
# simulator/promisify linked to common/promisify (branch validation not shown, but checked)
cdieringer@Snapper-osx:~/node/coinstac-simulator$ ll node_modules/ | grep coinstac
lrwxr-xr-x    1 cdieringer  staff     57 Jun  7 11:40 coinstac-common@ -> ../../../../../usr/local/lib/node_modules/coinstac-common
...
# algo-integration linked to sim and bisect converge
cdieringer@Snapper-osx:~/node/coinstac-decentralized-algorithm-integration$ ll node_modules/ | grep coinstac
lrwxr-xr-x    1 cdieringer  staff     57 Jun  7 20:55 coinstac-common@ -> ../../../../../usr/local/lib/node_modules/coinstac-common # <== actually unnecssary :)
lrwxr-xr-x    1 cdieringer  staff     72 Jun  6 10:18 coinstac-example-computation-bisect-converge@ -> /usr/local/lib/node_modules/coinstac-example-computation-bisect-converge
lrwxr-xr-x    1 cdieringer  staff     60 Jun  7 20:58 coinstac-simulator@ -> ../../../../../usr/local/lib/node_modules/coinstac-simulator
cdieringer@Snapper-osx:~/node/coinstac-decentralized-algorithm-integration$ node test/
info: db server up
info: db seeded
info: compute server up
info: clients up
info: USER: brittny ...bumping 1
info: COMPUTE-SERVER: [ { un: 'brittny', data: 1 } ]
info: USER: runtang ...bumping 1
info: USER: margaret ...bumping 1
info: USER: vince ...bumping 1
info: COMPUTE-SERVER: [ { un: 'brittny', data: 1 }, { un: 'runtang', data: 1 } ]
info: COMPUTE-SERVER: [ { un: 'brittny', data: 1 },
  { un: 'margaret', data: 1 },
  { un: 'runtang', data: 1 } ]
info: COMPUTE-SERVER: [ { un: 'brittny', data: 1 },
  { un: 'margaret', data: 1 },
  { un: 'runtang', data: 1 },
  { un: 'vince', data: 1 } ]
info: USER: margaret ...bumping 2
info: USER: brittny ...bumping 2
info: USER: runtang ...bumping 2
info: USER: vince ...bumping 2
info: COMPUTE-SERVER: [ { un: 'brittny', data: 2 },
  { un: 'margaret', data: 1 },
  { un: 'runtang', data: 1 },
  { un: 'vince', data: 1 } ]
info: COMPUTE-SERVER: [ { un: 'brittny', data: 2 },
  { un: 'margaret', data: 2 },
  { un: 'runtang', data: 1 },
  { un: 'vince', data: 1 } ]
info: COMPUTE-SERVER: [ { un: 'brittny', data: 2 },
  { un: 'margaret', data: 2 },
  { un: 'runtang', data: 2 },
  { un: 'vince', data: 1 } ]
info: COMPUTE-SERVER: [ { un: 'brittny', data: 2 },
  { un: 'margaret', data: 2 },
  { un: 'runtang', data: 2 },
  { un: 'vince', data: 2 } ]
info: USER: brittny ...bumping 3
info: USER: margaret ...bumping 3
info: USER: vince ...bumping 3
info: USER: runtang ...bumping 3
info: COMPUTE-SERVER: [ { un: 'brittny', data: 3 },
  { un: 'margaret', data: 2 },
  { un: 'runtang', data: 2 },
  { un: 'vince', data: 2 } ]
info: COMPUTE-SERVER: [ { un: 'brittny', data: 3 },
  { un: 'margaret', data: 3 },
  { un: 'runtang', data: 2 },
  { un: 'vince', data: 2 } ]
info: COMPUTE-SERVER: [ { un: 'brittny', data: 3 },
  { un: 'margaret', data: 3 },
  { un: 'runtang', data: 2 },
  { un: 'vince', data: 3 } ]
info: COMPUTE-SERVER: [ { un: 'brittny', data: 3 },
  { un: 'margaret', data: 3 },
  { un: 'runtang', data: 3 },
  { un: 'vince', data: 3 } ]
info: COMPUTE-SERVER: info: computation complete, run test_run_id
info: db server up
info: db seeded
info: compute server up
info: clients up
info: COMPUTE-SERVER: 1
info: USER: brittny 11
info: USER: margaret 11
info: USER: vince 11
info: USER: runtang 11
info: COMPUTE-SERVER: 2
info: USER: vince 12
info: USER: runtang 12
info: USER: margaret 12
info: USER: brittny 12
info: COMPUTE-SERVER: 3
info: USER: brittny 13
info: USER: runtang 13
info: USER: vince 13
info: USER: margaret 13
info: COMPUTE-SERVER: 4
info: USER: vince 14
info: USER: brittny 14
info: USER: margaret 14
info: USER: runtang 14
info: COMPUTE-SERVER: 5
info: COMPUTE-SERVER: info: computation complete, run test_run_id
info: db server up
info: db seeded
info: compute server up
info: clients up
error: USER: minionA I read and parsed a file.  It's value is: A
info: COMPUTE-SERVER: { minionA: { value: 'A' } }
error: USER: minionB I read and parsed a file.  It's value is: B
info: COMPUTE-SERVER: { minionA: { value: 'A' },
  minionB: { value: 'B' },
  complete: true }
info: COMPUTE-SERVER: info: computation complete, run test_run_id
info: db server up
info: db seeded
info: compute server up
info: clients up
error: USER: jill reading files from dir: jills-data
error: COMPUTE-SERVER: { jill: { 'data1.txt': 1, 'data2.bat': 2 } }
error: USER: chris reading files from dir: chris-data
error: COMPUTE-SERVER: { jill: { 'data1.txt': 1, 'data2.bat': 2 },
  chris: { 'data3.txt': 3, 'data4.anything': 4 },
  complete: true }
info: COMPUTE-SERVER: info: computation complete, run test_run_id
info: db server up
info: db seeded
info: compute server up
info: clients up
error: USER: sandeep caught per expectation
error: USER: sandeep caught per expectation
error: USER: prema caught per expectation
info: COMPUTE-SERVER: info: computation complete, run test_run_id
info: db server up
info: db seeded
info: compute server up
info: clients up
error: USER: jamin My random # was 50
error: USER: sergey My random # was 92
error: USER: drew My random # was 15
error: USER: ross My random # was 20
error: COMPUTE-SERVER: My random # was 48
info: USER: jamin old 50 new 49
info: USER: drew old 15 new 31.5
info: USER: sergey old 92 new 70
info: USER: ross old 20 new 34
info: USER: drew old 31.5 new 39.75
info: USER: sergey old 70 new 59
info: USER: ross old 34 new 41
info: USER: jamin old 49 new 48.5
info: USER: sergey old 59 new 53.5
error: USER: sergey (node:60244) Warning: Possible EventEmitter memory leak detected. 21 error listeners added. Use emitter.setMaxListeners() to increase limit
info: USER: ross old 41 new 44.5
error: USER: ross (node:60246) Warning: Possible EventEmitter memory leak detected. 21 error listeners added. Use emitter.setMaxListeners() to increase limit
info: USER: drew old 39.75 new 43.875
error: USER: drew (node:60245) Warning: Possible EventEmitter memory leak detected. 21 error listeners added. Use emitter.setMaxListeners() to increase limit
info: USER: jamin old 48.5 new 48.25
error: USER: jamin (node:60243) Warning: Possible EventEmitter memory leak detected. 21 error listeners added. Use emitter.setMaxListeners() to increase limit
error: COMPUTE-SERVER: (node:60235) Warning: Possible EventEmitter memory leak detected. 21 error listeners added. Use emitter.setMaxListeners() to increase limit
info: USER: ross old 44.5 new 46.25
info: USER: sergey old 53.5 new 50.75
info: USER: drew old 43.875 new 45.9375
info: USER: jamin old 48.25 new 48.125
info: USER: jamin old 48.125 new 48.0625
info: USER: drew old 45.9375 new 46.96875
info: USER: sergey old 50.75 new 49.375
info: USER: ross old 46.25 new 47.125
info: COMPUTE-SERVER: all users converged on 48 [ { final: 46.96875, username: 'drew' },
  { final: 48.0625, username: 'jamin' },
  { final: 47.125, username: 'ross' },
  { final: 49.375, username: 'sergey' } ]
info: COMPUTE-SERVER: info: computation complete, run test_run_id
```

**Comment by cdaringe** [comment]
Nm... was able to reproduce!  Will fix!

**Comment by cdaringe** [comment]
issues ^^ now resolved. must pull. thx!

**Pull request merged**
